### ISSUE TITLE
[BUG] Console error and no animation playing (for previously configured animations, prior to 0.5.0)

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#148]
Hello,

Thx for the latest release!
Using 0.5.0

I'm trying to convert old animations that don't work anymore.
But I get this error message and no animation after modifying the item animation:
![image](https://user-images.githubusercontent.com/1687854/126911593-fe91cb8a-3562-489f-b538-821fc8729173.png)
![image](https://user-images.githubusercontent.com/1687854/126911590-68957a1c-ec5c-49b1-8f91-d2439cad2a34.png)

Not sure how it was configured before the update :/

**Comment by otigon** [comment]
It looks like I had a line pointing in the wrong direction for the custom path there. I'll push a fix later, but for now you can choose that exact animation without going the custom route, it's in the menus for that Aniamtion Type

**Comment by DarKDinDoN** [comment]
@otigon thx for the reply, didn't even notice it was there :)

Quick question, radius is tied to grid settings now? Was it before?
I usually place tokens on world maps, so my players can keep track of their character HP and other stuff. I think, but might be mistaken, that prior to 0.5.0 the radius was based more on token size (ie: 2 means 2 times the token size) than actual grid size. So that when animations were played on such maps, the animations were still visible.

**Comment by otigon** [comment]
The custom setting issue is fixed as of 0.5.01.

Scaling, for most animations, is based off the Token size. Scaling for things like the Explosions and the Self/Target effects is based off the grid size, taking into account Distance. I didn't consider a use case like you mention, so I might revisit that

**Comment by otigon** [comment]
I just pushed 0.5.02 that includes the change for the Radius call. It now reads the input as per grid square rather than translating the distance on the scene

**Comment by DarKDinDoN** [comment]
@otigon Hi,

Thx the changes :)
Tho, I still have that error on custom self effect: 
![image](https://user-images.githubusercontent.com/1687854/126965201-ed2a2ca3-89e9-492b-aedf-53e3ac8ec29a.png)
![image](https://user-images.githubusercontent.com/1687854/126965245-954a444b-35de-4fc2-9d2e-5c73f5730126.png)

**Comment by otigon** [comment]
Can you export the item and send it to me on Discord so I can test it?

**Comment by otigon** [comment]
Found the issue for the item. This is solely on the Automated Animations end and I'll push a fix today after work

**Comment by otigon** [comment]
Ok.. this should be fixed now with 0.5.04. Sorry for the confusion, and let me know if anything else pops up
