### ISSUE TITLE
Template animations are played on the next template when using BetterRolls5e

### ISSUE THREAD

**Issue by Ro4m3r** [otigon/automated-jb2a-animations#168]
If BetterRolls5e is installed, template animations will play on the next template instead of on the template that is created when casting the spell.

Example
![example](https://user-images.githubusercontent.com/21060784/128212327-a2e12a0d-6ece-4069-8ff5-1761e4660dd4.mp4)

**Comment by otigon** [comment]
This should be resolved on the next update today/tomorrow, but I'll double check with just Better Rolls

**Comment by Ro4m3r** [comment]
There is also something else that may be related, although this may also be fixed by your fix.

Basically, it seems your module hooks damage rolls, and then queues the animation onto the next template. This creates a problem, as the animation can be played twice. 

Here's an example video:
https://user-images.githubusercontent.com/21060784/128225338-e7d5a6aa-6f78-4efd-a218-48b64eaead83.mp4

Thanks for the quick response!

**Comment by otigon** [comment]
Should be fixed with what I've done for the next release but I'll verify

**Comment by Ro4m3r** [comment]
Awesome. There's something else I found that is probably related, so I'll post this here in case it isn't fixed and you need help finding bugs. But it is very likely related.

If you set the template to auto-delete, the next drawn template will throw an error.


https://user-images.githubusercontent.com/21060784/128243155-1ea329c8-d07e-430f-9e5a-29364d5e1f5c.mp4

**Comment by otigon** [comment]
This should be working as intended as of the 0.5.15 release
