### ISSUE TITLE
Bug: broken "return" functionality causing issues in 3.1.4

### ISSUE THREAD

**Issue by zk-sn** [otigon/automated-jb2a-animations#395]
While setting up a new campaign last night, I updated to the newest 3.1.4 version and found that automated animations stopped working, particularily for "eldritch blast" but assuming also for others.

When I investigated using the console, I got an error:
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[Detected 1 package: autoanimations]
    at Function.keys (<anonymous>)
    at buildFile (build-filepath.js:46)
    at rangedAnimations (rangedAnimation.js:18)

I put a breakpoint at build-filepath:46 which is this line:
const returnArray = Object.keys(jb2a.return.weapon);

It looks like the problem is that jb2a.return.weapon is null in the new version.  I reverted to 3.1.3 and it's working fine again.

**Comment by zk-sn** [comment]
build-filepath:46 from version 3.1.3 didn't have the .weapon there:
const returnArray = Object.keys(jb2a.return);

**Comment by otigon** [comment]
Try updating to 3.1.5, should work now

**Comment by animerunt** [comment]
I am on 3.1.5 and still getting this error for ranged and melee:

build-filepath.js:46 
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[Detected 1 package: autoanimations]
    at Function.keys (<anonymous>)
    at buildFile (build-filepath.js:46:36)
    at rangedAnimations (rangedAnimation.js:18:26)

build-filepath.js:46 
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[Detected 1 package: autoanimations]
    at Function.keys (<anonymous>)
    at buildFile (build-filepath.js:46:36)
    at meleeAnimation (meleeAnimation.js:39:26)

**Comment by otigon** [comment]
The pathway exists in both databases, so I suspect you may need to reinstall A-A and do a fresh install. Be sure to export you existing AutoRec menu before doing so

**Comment by animerunt** [comment]
I had tried removing and adding before but this time I removed A-A, socetlib, and sequencer, then added them back and it started working again. thanks!

**Comment by otigon** [comment]
Excellent, glad you got it fixed!
