### ISSUE TITLE
[BUG] - PF1E Animations broke with new v9 release of system

### ISSUE THREAD

**Issue by Hevkalol** [otigon/automated-jb2a-animations#664]
**Describe the bug**
Animations  doesnt work anymore in pf1e v9

 

**Screenshots**
![image](https://github.com/otigon/automated-jb2a-animations/assets/131466739/d8865029-5d0c-4b9e-9746-8b4a8c062fb6)

**Setup:**
 - Foundry Version: [e.g. 10.291]
 - System Version: [pf1e v9]
 - Sequencer Version: [e.g. 3.1.2]
 - Automated Animations version 4,2,61
 - Hosting Location (Local)
 - Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations

**Comment by Hevkalol** [comment]
Fixed with latest release.

**Comment by DrMcCoy** [comment]
Still doesn't seem to work with PF1e 9.3, Foundry VTT 10.303 and Automated Animations 4.2.62, for the most part.

Condition animations (i.e. Active Effects) work, but attack (Melee, Range) and spell animations (On Token, Template) don't fire at all.
